export const COUNTRIES = {
    AUSTRALIA: "Australia",
    CANADA: "Canada",
    DENMARK: "Denmark",
    FINLAND: "Finland",
    FRANCE: "France",
    GERMANY: "Germany",
    INDIA: "India",
    IRELAND: "Ireland",
    ITALY: "Italy",
    NETHERLANDS: "Netherlands",
    NEW_ZEALAND: "New Zealand",
    NORWAY: "Norway",
    SPAIN: "Spain",
    SWEDEN: "Sweden",
    SWITZERLAND: "Switzerland",
    UNITED_KINGDOM: "United Kingdom",
    UNITED_STATES: "United States",
} as const;